run:
  skip-dirs:
    - vendor
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
  disable:
    - typecheck  # 異なるディレクトリの型チェックエラーを無視

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8