run:
  skip-dirs:
    - vendor
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
  disable:
    - typecheck  # 異なるディレクトリの型チェックエラーを無視

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8

run:
  timeout: 5m
  tests: false
  # 全てのパッケージを個別に解析
  skip-dirs-use-default: false
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused