version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hato
      POSTGRES_PASSWORD: hato72
      POSTGRES_DB: hato
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  test-db:
    image: postgres:latest
    container_name: test-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: hato
      POSTGRES_PASSWORD: hato72
      POSTGRES_DB: hato_test
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - PORT=8080
      - POSTGRES_USER=hato
      - POSTGRES_PW=hato72
      - POSTGRES_DB=hato
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - GO_ENV=dev
      - SECRET=uu5pveql
      - API_DOMAIN=localhost
      - FE_URL=http://localhost:3000
    volumes:
      - ./backend:/app/backend
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
