services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./backend:/app
    # environment:
    #   POSTGRES_USER: hato
    #   POSTGRES_PASSWORD: hato72
    #   POSTGRES_DB: hato
    networks:
      - lesson
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Tokyo
    ports:
      - 5434:5432
    # env_file:
    #   - ./backend/.env.dev
    networks:
      - lesson

networks:
  lesson:
