name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: hato
          POSTGRES_PASSWORD: hato72
          POSTGRES_DB: hato_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        cd backend
        go mod download

    - name: Create test directories
      run: |
        cd backend
        mkdir -p user_images/icons
        mkdir -p cuisine_images/cuisine_icons

    - name: Run Tests
      run: |
        cd backend
        go test -v ./...
      env:
        POSTGRES_USER: hato
        POSTGRES_PASSWORD: hato72
        POSTGRES_DB: hato_test
        POSTGRES_PORT: 5432
        POSTGRES_HOST: localhost
        GO_ENV: test
        SECRET: test_secret

  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/go-backend:latest

    # ここにデプロイ先のサービスに応じたデプロイステップを追加
    # 例: Render, Heroku, GCP等へのデプロイ設定
    - name: Deploy to Render 
      uses: ttskch/render-deploy@v1.0.0
      with:
        api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        interval: 20 # optional
        timeout: 300 # optional