name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

gcp_env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: cookmeet-go-backend
  REGION: asia-southeast1

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Notest]')"
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: hato
          POSTGRES_PASSWORD: hato72
          POSTGRES_DB: hato_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        cd backend
        go mod download

    - name: Create test directories
      run: |
        cd backend
        mkdir -p user_images/icons
        mkdir -p cuisine_images/cuisine_icons

    - name: Run Tests
      run: |
        cd backend
        go test -v ./...
      env:
        POSTGRES_USER: hato
        POSTGRES_PASSWORD: hato72
        POSTGRES_DB: hato_test
        POSTGRES_PORT: 5432
        POSTGRES_HOST: localhost
        GO_ENV: test
        SECRET: test_secret

  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_USERNAME }}/go-backend:latest  

    # GCP認証
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    # GCP CLIのセットアップ
    - uses: google-github-actions/setup-gcloud@v1
    
    # Dockerイメージのビルドとプッシュ
    - name: Build and push Docker image
      run: |-
        gcloud auth configure-docker
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/go-backend:latest

    # Cloud Runへのデプロイ
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated

    # ここにデプロイ先のサービスに応じたデプロイステップを追加
    # 例: Render, Heroku, GCP等へのデプロイ設定
    # - name: Deploy to Render 
    #   uses: ttskch/render-deploy@v1.0.0
    #   with:
    #     api-key: ${{ secrets.RENDER_API_KEY }}
    #     service-id: ${{ secrets.RENDER_SERVICE_ID }}
    #     interval: 20 # optional
    #     timeout: 500 # optional

    # Cloud Runへのデプロイ
    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud run deploy cookmeet-go-backend \
    #       --image ${{ secrets.DOCKER_USERNAME }}/go-backend:latest \
    #       --platform managed \
    #       --region asia-southeast1 \
    #       --allow-unauthenticated