name: Super Lint Code Base

# Documentation:
# https://github.com/github/super-linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Super Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          cd backend
          go mod download

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          # 追加: Markdownの検証を無効化
          VALIDATE_MARKDOWN: false
          VALIDATE_ENV: false
          VALIDATE_CHECKOV: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
